# pandas的拼接操作

pandas的拼接分为两种：
- 级联：pd.concat, pd.append
- 合并：pd.merge, pd.join

In [4]:
import numpy as np
from pandas import DataFrame, Series
import pandas as pd

## 0. 回顾numpy的级联

============================================

练习12：

1. 生成2个3*3的矩阵，对其分别进行两个维度上的级联

============================================

In [2]:
n1 = np.random.randint(1, 10, size=(3, 3))
n2 = np.random.randint(1, 10, size=(3, 3))
display(n1, n2)

array([[8, 4, 2],
       [9, 1, 4],
       [3, 3, 3]])

array([[5, 6, 7],
       [1, 4, 4],
       [2, 3, 6]])

In [3]:
np.concatenate((n1, n2)) # 默认水平级联

array([[8, 4, 2],
       [9, 1, 4],
       [3, 3, 3],
       [5, 6, 7],
       [1, 4, 4],
       [2, 3, 6]])

In [4]:
np.vstack((n1, n2))

array([[8, 4, 2],
       [9, 1, 4],
       [3, 3, 3],
       [5, 6, 7],
       [1, 4, 4],
       [2, 3, 6]])

In [6]:
np.concatenate((n1, n2), axis=1)

array([[8, 4, 2, 5, 6, 7],
       [9, 1, 4, 1, 4, 4],
       [3, 3, 3, 2, 3, 6]])

In [9]:
np.hstack((n1, n2))

array([[8, 4, 2, 5, 6, 7],
       [9, 1, 4, 1, 4, 4],
       [3, 3, 3, 2, 3, 6]])

为方便讲解，我们首先定义一个生成DataFrame的函数：

In [12]:
def make_df(index, cols):
    df = DataFrame({col: [col + str(i) for i in index] for col in cols})
    df.index=index
    return df

In [13]:
make_df([1, 2, 3, 4], list('ABCD'))

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

## 1. 使用pd.concat()级联

pandas使用pd.concat函数，与np.concatenate函数类似，只是多了一些参数：
```
objs
axis=0
join='outer'
join_axes=None
ignore_index=False
keys = [value1,value2...]
```

### 1)  简单级联

和np.concatenate一样，优先增加行数（默认axis=0）

In [14]:
df1 = make_df([1, 2, 3, 4], list('ABCD'))
df2 = make_df([1, 2, 3, 4], list('ABCD'))
display(df1, df2)

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [15]:
pd.concat((df1, df2))

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

可以通过设置axis来改变级联方向

In [16]:
pd.concat((df1, df2), axis=1)

A   B   C   D   A   B   C   D
1  A1  B1  C1  D1  A1  B1  C1  D1
2  A2  B2  C2  D2  A2  B2  C2  D2
3  A3  B3  C3  D3  A3  B3  C3  D3
4  A4  B4  C4  D4  A4  B4  C4  D4

级连会把该方向上索引相同的元素放在一行（一列），index/columns在级联时可以重复

也可以选择忽略ignore_index，重新索引

In [17]:
pd.concat((df1, df2), ignore_index=True)

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4
4  A1  B1  C1  D1
5  A2  B2  C2  D2
6  A3  B3  C3  D3
7  A4  B4  C4  D4

或者使用多层索引 keys  

concat([x,y],keys=['x','y'])

In [18]:
pd.concat((df1, df2), keys=['一班', '二班'])

A   B   C   D
一班 1  A1  B1  C1  D1
   2  A2  B2  C2  D2
   3  A3  B3  C3  D3
   4  A4  B4  C4  D4
二班 1  A1  B1  C1  D1
   2  A2  B2  C2  D2
   3  A3  B3  C3  D3
   4  A4  B4  C4  D4

In [19]:
# 检查是否有重复索引,有重复索引就不能级联
pd.concat((df1, df2), verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([1, 2, 3, 4], dtype='int64')

============================================

练习13：

1. 想一想级联的应用场景？

2. 使用昨天的知识，建立一个期中考试张三、李四的成绩表ddd

3. 假设新增考试学科"计算机"，如何实现？

4. 新增王老五同学的成绩，如何实现？

============================================

In [21]:
index = ['张三', '李四', '王五', '赵六']
columns = ['语文', '数学', '英语', 'Python']
data = np.random.randint(0, 150, size=(4, 4))
df = DataFrame(data=data, index=index, columns=columns)
df

语文   数学   英语  Python
张三   88  114  133     139
李四   75   78   85       2
王五   78  127  140      53
赵六  130  142   28      38

In [23]:
df.loc[:, '计算机'] = np.random.randint(0, 150, size=(4, 1))
df

语文   数学   英语  Python  计算机
张三   88  114  133     139  118
李四   75   78   85       2    9
王五   78  127  140      53  105
赵六  130  142   28      38   22

In [26]:
df.drop(columns=['计算机'])

语文   数学   英语  Python
张三   88  114  133     139
李四   75   78   85       2
王五   78  127  140      53
赵六  130  142   28      38

In [27]:
computer = DataFrame(data=np.random.randint(0, 150, size=(4,1)), index=df.index, columns=['计算机'])
computer

计算机
张三  113
李四  148
王五   69
赵六   91

In [28]:
pd.concat((df, computer), axis=1)

语文   数学   英语  Python  计算机  计算机
张三   88  114  133     139  118  113
李四   75   78   85       2    9  148
王五   78  127  140      53  105   69
赵六  130  142   28      38   22   91

In [44]:
df.drop(columns=['计算机'], inplace=True)

In [52]:
df

语文   数学   英语  Python
张三    88  114  133     139
李四    75   78   85       2
王五    78  127  140      53
赵六   130  142   28      38
王老五  122   38  144      91

In [46]:
df.loc['王老五'] = np.random.randint(0, 150, size=4)

In [56]:
df.drop(index=['王老五'], inplace=True)

KeyError: "['王老五'] not found in axis"

In [57]:
df

语文   数学   英语  Python
张三   88  114  133     139
李四   75   78   85       2
王五   78  127  140      53
赵六  130  142   28      38

In [60]:
wanglaowu = DataFrame(data=np.random.randint(0, 150, size=(1, 4)), index=['王老五'], columns=df.columns)
wanglaowu

语文   数学  英语  Python
王老五  94  105  37      42

In [62]:
pd.concat((df, wanglaowu))

语文   数学   英语  Python
张三    88  114  133     139
李四    75   78   85       2
王五    78  127  140      53
赵六   130  142   28      38
王老五   94  105   37      42

### 2) 不匹配级联

不匹配指的是级联的维度的索引不一致。例如纵向级联时列索引不一致，横向级联时行索引不一致

In [63]:
df1 = make_df([1, 2, 3, 4], cols=list('ABCD'))
df2 = make_df([2, 3, 4, 5], cols=list('BCDE'))
display(df1, df2)

A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

B   C   D   E
2  B2  C2  D2  E2
3  B3  C3  D3  E3
4  B4  C4  D4  E4
5  B5  C5  D5  E5

In [64]:
# 不匹配级联: 会自动把索引的位置进行级联, 不匹配的位置补NaN
pd.concat((df1, df2))

A   B   C   D    E
1   A1  B1  C1  D1  NaN
2   A2  B2  C2  D2  NaN
3   A3  B3  C3  D3  NaN
4   A4  B4  C4  D4  NaN
2  NaN  B2  C2  D2   E2
3  NaN  B3  C3  D3   E3
4  NaN  B4  C4  D4   E4
5  NaN  B5  C5  D5   E5

In [65]:
pd.concat((df1, df2), axis=1) # 外链接

A    B    C    D    B    C    D    E
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   C2   D2   E2
3   A3   B3   C3   D3   B3   C3   D3   E3
4   A4   B4   C4   D4   B4   C4   D4   E4
5  NaN  NaN  NaN  NaN   B5   C5   D5   E5

有3种连接方式：

- 外连接：补NaN（默认模式）

- 内连接：只连接匹配的项

In [66]:
pd.concat((df1, df2), axis=1, join='inner')

A   B   C   D   B   C   D   E
2  A2  B2  C2  D2  B2  C2  D2  E2
3  A3  B3  C3  D3  B3  C3  D3  E3
4  A4  B4  C4  D4  B4  C4  D4  E4

- 连接指定轴 join_axes

============================================

练习14：

    假设【期末】考试ddd2的成绩没有张三的，只有李四、王老五、赵小六的，使用多种方法级联

============================================

### 3) 使用append()函数添加

In [69]:
df1.append(df2, ignore_index=True)

A   B   C   D    E
0   A1  B1  C1  D1  NaN
1   A2  B2  C2  D2  NaN
2   A3  B3  C3  D3  NaN
3   A4  B4  C4  D4  NaN
4  NaN  B2  C2  D2   E2
5  NaN  B3  C3  D3   E3
6  NaN  B4  C4  D4   E4
7  NaN  B5  C5  D5   E5

由于在后面级联的使用非常普遍，因此有一个函数append专门用于在后面添加

============================================

练习15：

    新建一个只有张三李四王老五的期末考试成绩单ddd3，使用append()与期中考试成绩表ddd级联

============================================

使用pd.read...读取文件

## 2. 使用pd.merge()合并

merge与concat的区别在于，merge需要依据某一共同的行或列来进行合并

使用pd.merge()合并时，会自动根据两者相同column名称的那一列，作为key来进行合并。

注意每一列元素的顺序不要求一致

###  1) 一对一合并

In [70]:
df1 = DataFrame({'name':['张三','李四','Chales'],'id':[1,2,3],'age':[22,21,25]})

df2 = DataFrame({'sex':['男','男','女'],'id':[2,3,4],'group':['sale','search','service']})
display(df1, df2)

name  id  age
0      张三   1   22
1      李四   2   21
2  Chales   3   25

sex  id    group
0   男   2     sale
1   男   3   search
2   女   4  service

In [71]:
pd.merge(df1, df2)

name  id  age sex   group
0      李四   2   21   男    sale
1  Chales   3   25   男  search

### 2) 多对一合并

In [72]:
df1 = DataFrame({'name':['张三','李四','Chales'],'id':[1,2,2],'age':[22,21,25]})

df2 = DataFrame({'sex':['男','男','女'],'id':[2,3,4],'group':['sale','search','service']})
display(df1,df2)

name  id  age
0      张三   1   22
1      李四   2   21
2  Chales   2   25

sex  id    group
0   男   2     sale
1   男   3   search
2   女   4  service

In [73]:
df1.merge(df2)

name  id  age sex group
0      李四   2   21   男  sale
1  Chales   2   25   男  sale

### 3) 多对多合并

In [75]:
df1 = DataFrame({'name':['张三','李四','张三'],'salary':[10000,12000,20000],'age':[22,21,25]})

df2 = DataFrame({'sex':['男','男','女'],'name':['张三','张三','凡凡'],'group':['sale','search','service']})
display(df1, df2)

name  salary  age
0   张三   10000   22
1   李四   12000   21
2   张三   20000   25

sex name    group
0   男   张三     sale
1   男   张三   search
2   女   凡凡  service

In [76]:
df1.merge(df2)

name  salary  age sex   group
0   张三   10000   22   男    sale
1   张三   10000   22   男  search
2   张三   20000   25   男    sale
3   张三   20000   25   男  search

### 4) key的规范化

- 使用on=显式指定哪一列为key,当有多个key相同时使用

In [77]:
df1 = DataFrame({'name':['张三','李四','张三'],'salary':[10000,12000,20000],'age':[22,21,25]})

df2 = DataFrame({'age':[21,18,29],'name':['张三','张三','凡凡'],'group':['sale','search','service']})
display(df1, df2)

name  salary  age
0   张三   10000   22
1   李四   12000   21
2   张三   20000   25

age name    group
0   21   张三     sale
1   18   张三   search
2   29   凡凡  service

In [78]:
# 如果有多个相同列的事情, 使用on指定具体要用哪一列来合并
df1.merge(df2, on='name')

name  salary  age_x  age_y   group
0   张三   10000     22     21    sale
1   张三   10000     22     18  search
2   张三   20000     25     21    sale
3   张三   20000     25     18  search

- 使用left_on和right_on指定左右两边的列作为key，当左右两边的key都不相等时使用

In [79]:
df1 = DataFrame({'name':['张三','李四','张三'],'salary':[10000,12000,20000],'age':[22,21,25]})

df2 = DataFrame({'年龄':[21,18,29],'名字':['张三','张三','凡凡'],'group':['sale','search','service']})
display(df1, df2)

name  salary  age
0   张三   10000   22
1   李四   12000   21
2   张三   20000   25

年龄  名字    group
0  21  张三     sale
1  18  张三   search
2  29  凡凡  service

In [80]:
df1.merge(df2, left_on='name', right_on='名字')

name  salary  age  年龄  名字   group
0   张三   10000   22  21  张三    sale
1   张三   10000   22  18  张三  search
2   张三   20000   25  21  张三    sale
3   张三   20000   25  18  张三  search

当左边的列和右边的index相同的时候,使用right_index=True

In [81]:
df1 = DataFrame({'name':['张三','李四','张三'],'salary':[10000,12000,20000],'age':[22,21,25]})

df2 = DataFrame({'年龄':[21,18,29],'名字':['张三','张三','凡凡'],'group':['sale','search','service']},
                index = [22,21,25])
display(df1,df2)

name  salary  age
0   张三   10000   22
1   李四   12000   21
2   张三   20000   25

年龄  名字    group
22  21  张三     sale
21  18  张三   search
25  29  凡凡  service

In [83]:
df1.merge(df2, left_on='age', right_index=True)

name  salary  age  年龄  名字    group
0   张三   10000   22  21  张三     sale
1   李四   12000   21  18  张三   search
2   张三   20000   25  29  凡凡  service

============================================

练习16：

1. 假设有两份成绩单，除了ddd是张三李四王老五之外，还有ddd4是张三和赵小六的成绩单，如何合并？

2. 如果ddd4中张三的名字被打错了，成为了张十三，怎么办？

3. 自行练习多对一，多对多的情况  

4. 自学left_index,right_index

============================================

### 5) 内合并与外合并

- 内合并：只保留两者都有的key（默认模式）

In [ ]:
df1 = DataFrame({'name':['张三','李四','张三'],'salary':[10000,12000,20000],'age':[22,21,25]})

df2 = DataFrame({'age':[21,18,29],'名字':['张三','张三','凡凡'],'group':['sale','search','service']})
display(df1, df2)

- 外合并 how='outer'：补NaN

- 左合并、右合并：how='left'，how='right'，

============================================

练习17：



1. 考虑应用情景，使用多种方式合并ddd与ddd4

============================================

### 6) 列冲突的解决

当列冲突时，即有多个列名称相同时，需要使用on=来指定哪一个列作为key，配合suffixes指定冲突列名

In [3]:
#期中
df1 = DataFrame({'name':['张三','李四','张三'],'degree':[120,118,149],'age':[22,21,25]})

#期末考试
df2 = DataFrame({'degree':[99,97,129],'name':['张三','张三','凡凡'],'group':['sale','search','service']})
display(df1, df2)

name  degree  age
0   张三     120   22
1   李四     118   21
2   张三     149   25

degree name    group
0      99   张三     sale
1      97   张三   search
2     129   凡凡  service

可以使用suffixes=自己指定后缀

============================================

练习18：

    假设有两个同学都叫李四，ddd5、ddd6都是张三和李四的成绩表，如何合并？

============================================

## 作业
## 3. 案例分析：美国各州人口数据分析

作业知识补充

In [127]:
# unique() 去重函数
s = Series(['Tom','Lucy','Tom','dancer','Lucy'])

In [128]:
s.unique()

array(['Tom', 'Lucy', 'dancer'], dtype=object)

In [1]:
n = DataFrame({'name':['Tom','Lucy','Tom','dancer','Lucy'],'age':[12,13,12,11,15]})
n

NameError: name 'DataFrame' is not defined

In [1]:
# query 条件查询函数
n.query("name == 'Lucy' & age>14")  

NameError: name 'n' is not defined

首先导入文件，并查看数据样本

In [12]:
s_abb = pd.read_csv('../data/state-abbrevs.csv')
s_abb.head()

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [15]:
s_pop = pd.read_csv('../data/state-population.csv')
s_pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [16]:
s_ares = pd.read_csv('../data/state-areas.csv')
s_ares.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

合并pop与abbrevs两个DataFrame，分别依据state/region列和abbreviation列来合并。

为了保留所有信息，使用外合并。

In [17]:
s_abb.merge(s_pop, left_on='abbreviation', right_on='state/region', how='outer')

state abbreviation state/region     ages  year   population
0     Alabama           AL           AL  under18  2012    1117489.0
1     Alabama           AL           AL    total  2012    4817528.0
2     Alabama           AL           AL  under18  2010    1130966.0
3     Alabama           AL           AL    total  2010    4785570.0
4     Alabama           AL           AL  under18  2011    1125763.0
...       ...          ...          ...      ...   ...          ...
2539      NaN          NaN          USA    total  2010  309326295.0
2540      NaN          NaN          USA  under18  2011   73902222.0
2541      NaN          NaN          USA    total  2011  311582564.0
2542      NaN          NaN          USA  under18  2012   73708179.0
2543      NaN          NaN          USA    total  2012  313873685.0

[2544 rows x 6 columns]

去除abbreviation的那一列（axis=1）

查看存在缺失数据的列。

使用.isnull().any()，只有某一列存在一个缺失数据，就会显示True。

查看缺失数据

根据数据是否缺失情况显示数据，如果缺失为True，那么显示

找到有哪些state/region使得state的值为NaN，使用unique()查看非重复值

为找到的这些state/region的state项补上正确的值，从而去除掉state这一列的所有NaN！

记住这样清除缺失数据NaN的方法！

合并各州面积数据areas，使用左合并。

思考一下为什么使用外合并？



继续寻找存在缺失数据的列

我们会发现area(sq.mi)这一列有缺失数据，为了找出是哪一行，我们需要找出是哪个state没有数据

去除含有缺失数据的行

查看数据是否缺失

找出2010年的全民人口数据,df.query(查询语句)

对查询结果进行处理，以state列作为新的行索引:set_index

计算人口密度。注意是Series/Series，其结果还是一个Series。

排序，并找出人口密度最高的五个州sort_values()

找出人口密度最低的五个州

要点总结：
- 统一用loc()索引
- 善于使用.isnull().any()找到存在NaN的列
- 善于使用.unique()确定该列中哪些key是我们需要的
- 一般使用外合并、左合并，目的只有一个：宁愿该列是NaN也不要丢弃其他列的信息

## 回顾：Series/DataFrame运算与ndarray运算的区别

- Series与DataFrame没有广播，如果对应index没有值，则记为NaN；或者使用add的fill_value来补缺失值
- ndarray有广播，通过重复已有值来计算