In [1]:
import numpy as np

### 11、给定一个4维矩阵，如何得到最后两维的和？

In [2]:
n11 = np.random.randint(0, 10, size=(2, 3, 4, 3))

In [ ]:
np.sum()

In [7]:
n11.sum(axis=(2, 3))

array([[64, 48, 51],
       [67, 55, 66]])

In [8]:
n11.sum(axis=(-1, -2))

array([[64, 48, 51],
       [67, 55, 66]])

### 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [10]:
# 最简单的方式采用逆向思维.
# 创建17个0的ndarray
n12 = np.zeros(shape=17)

In [11]:
n12[::4] = [1, 2, 3, 4, 5]

In [12]:
n12

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

### 13、给定一个二维矩阵，如何交换其中两行的元素？

In [21]:
n13 =  np.random.randint(0, 10, size=(6, 6))
n13

array([[2, 0, 4, 8, 2, 3],
       [4, 8, 2, 4, 2, 0],
       [8, 0, 5, 8, 2, 1],
       [0, 5, 1, 7, 0, 2],
       [5, 6, 5, 8, 7, 2],
       [3, 1, 4, 6, 8, 6]])

In [22]:
# 常规做法.
temp2 = n13[2].copy()
n13[2] = n13[3]
n13[3] = temp2
n13

array([[2, 0, 4, 8, 2, 3],
       [4, 8, 2, 4, 2, 0],
       [0, 5, 1, 7, 0, 2],
       [8, 0, 5, 8, 2, 1],
       [5, 6, 5, 8, 7, 2],
       [3, 1, 4, 6, 8, 6]])

In [18]:
# 高级技巧
n13[[1, 2, 1, 2, 3, 4, 0, 1]]

array([[9, 8, 4, 9, 1, 2],
       [7, 0, 8, 0, 3, 3],
       [9, 8, 4, 9, 1, 2],
       [7, 0, 8, 0, 3, 3],
       [5, 5, 6, 6, 6, 7],
       [7, 3, 8, 4, 4, 4],
       [8, 2, 9, 1, 0, 0],
       [9, 8, 4, 9, 1, 2]])

In [19]:
n13[[0, 1, 3, 2, 4, 5]]

array([[8, 2, 9, 1, 0, 0],
       [9, 8, 4, 9, 1, 2],
       [5, 5, 6, 6, 6, 7],
       [7, 0, 8, 0, 3, 3],
       [7, 3, 8, 4, 4, 4],
       [3, 6, 9, 2, 9, 6]])

In [20]:
n13[:, [1, 2, 3, 1, 2, 3]]

array([[2, 9, 1, 2, 9, 1],
       [8, 4, 9, 8, 4, 9],
       [0, 8, 0, 0, 8, 0],
       [5, 6, 6, 5, 6, 6],
       [3, 8, 4, 3, 8, 4],
       [6, 9, 2, 6, 9, 2]])

### 16、矩阵的每一行的元素都减去该行的平均值

In [23]:
n16 = np.random.randint(0, 10, size=(3, 5))
n16

array([[1, 8, 6, 5, 9],
       [4, 5, 2, 0, 7],
       [0, 6, 2, 5, 4]])

In [26]:
# 要求行的平均值,要对列进行聚合.
n16 - n16.mean(axis=1)

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [27]:
n16.mean(axis=1)

array([5.8, 3.6, 3.4])

In [29]:
n16

array([[1, 8, 6, 5, 9],
       [4, 5, 2, 0, 7],
       [0, 6, 2, 5, 4]])

In [28]:
n16 - n16.mean(axis=1).reshape(3, 1)

array([[-4.8,  2.2,  0.2, -0.8,  3.2],
       [ 0.4,  1.4, -1.6, -3.6,  3.4],
       [-3.4,  2.6, -1.4,  1.6,  0.6]])

In [30]:
n16.mean(axis=1).reshape(3, 1)

array([[5.8],
       [3.6],
       [3.4]])

### 17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：


In [32]:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

SyntaxError: invalid syntax (<ipython-input-32-8ca7b84a0e91>, line 1)

In [35]:
n17 = np.zeros(shape=(8,8), dtype='int')

In [36]:
n17[1::2, ::2] = 1
n17

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [37]:
n17[::2, 1::2] =1 
n17

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 18、正则化一个5*5随机矩阵
正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)


In [38]:
# 正则化, 也叫归一化, 把矩阵内的元素都变成0到1之间的小数
n18 = np.random.randint(0, 10, size=(4, 5))
n18

array([[0, 1, 5, 9, 3],
       [1, 3, 3, 3, 0],
       [4, 1, 6, 9, 7],
       [9, 7, 1, 1, 1]])

In [39]:
n18.min()

0

In [40]:
(n18 - n18.min()) / (n18.max() - n18.min())

array([[0.        , 0.11111111, 0.55555556, 1.        , 0.33333333],
       [0.11111111, 0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.44444444, 0.11111111, 0.66666667, 1.        , 0.77777778],
       [1.        , 0.77777778, 0.11111111, 0.11111111, 0.11111111]])