In [1]:
import numpy as np

In [4]:
np.eye(N=3, M=4, k=1, dtype='int')

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [7]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.full(shape=(3,2), fill_value=2)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [21]:
np.linspace(1, 50, num=50, endpoint=True, retstep=True, dtype='int')

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]), 1.0)

In [23]:
np.arange(1, 5, 2)

array([1, 3])

In [25]:
np.random.randn(1, 2, 3,)

array([[[ 0.23383405, -1.36559792,  0.53159114],
        [-0.39162614, -0.16300401,  1.23556599]]])

In [28]:
np.random.normal(loc=0, scale=1, size=(1, 2, 3))

array([[[-0.2970168 , -1.72163308, -0.52929853],
        [-1.33907156, -0.2221307 , -2.43592224]]])

In [29]:
np.random.randint(1200, 1500, size=(5, 3))

array([[1427, 1483, 1304],
       [1318, 1439, 1412],
       [1328, 1406, 1218],
       [1218, 1443, 1211],
       [1472, 1233, 1299]])

In [30]:
np.random.random(size=(5,3))

array([[0.46345121, 0.82589183, 0.34755601],
       [0.69338644, 0.21840643, 0.27944693],
       [0.19169975, 0.3203221 , 0.94151944],
       [0.42515362, 0.76796286, 0.0105996 ],
       [0.78879822, 0.97969391, 0.52414679]])

In [31]:
np.random.rand(5,3)

array([[0.10859014, 0.65559372, 0.08271343],
       [0.89501047, 0.43445034, 0.47485166],
       [0.42466028, 0.5207989 , 0.92310716],
       [0.69636619, 0.78962793, 0.45997257],
       [0.67697821, 0.88550703, 0.93907005]])