### 1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [3]:
import numpy as np

In [10]:
n = np.zeros(shape=10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
n[5] = 1
n

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

### 2、创建一个元素为从10到49的ndarray对象

In [14]:
n = np.array(range(10, 50))

In [15]:
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3、将第2题的所有元素位置反转

In [18]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [27]:
n = np.random.random(size=(10, 10))

In [28]:
n.min()

0.014185159662047586

In [29]:
np.min(n)

0.014185159662047586

### 5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [39]:
n = np.ones(shape=(10, 10), dtype=int)

In [40]:
n[1:-1, 1:-1] = 0
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 6、创建一个每一行都是从0到4的5*5矩阵

In [43]:
n = np.random.randint(0, 5, size=(5,5))

In [44]:
n

array([[1, 4, 4, 3, 2],
       [3, 2, 2, 4, 4],
       [0, 3, 0, 3, 0],
       [3, 4, 1, 3, 0],
       [2, 4, 3, 1, 1]])

### 7、创建一个范围在(0,1)之间的长度为12的等差数列

In [75]:
np.linspace(0, 1, num=12, endpoint=False, retstep=True)

(array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
        0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
        0.83333333, 0.91666667]), 0.08333333333333333)

### 8、创建一个长度为10的随机数组并排序

In [81]:
n = np.random.randint(0,10, size=10)
n

array([7, 4, 2, 9, 9, 6, 1, 0, 1, 7])

In [83]:
np.sort(n)

array([0, 1, 1, 2, 4, 6, 7, 7, 9, 9])

In [ ]:
n.sort
n

### 9、创建一个长度为10的随机数组并将最大值替换为0

In [50]:
n9 = np.random.randint(1, 10, size=10)
n9


array([1, 3, 6, 6, 4, 2, 4, 2, 4, 5])

In [51]:
n9.argmax()

2

In [52]:
index = [i for i in range(len(n)) if n9[i]==n9.max()]

for j in index:
    n9[j]=0
n9

array([1, 3, 0, 0, 4, 2, 4, 2, 4, 5])

### 10、创建一个5*5的矩阵,取出这个矩阵的第三列, 然后对这列数据进行排序.

In [147]:
n = np.random.randint(1, 10, size=(5,5))
n

array([[6, 4, 7, 7, 1],
       [1, 2, 4, 5, 8],
       [9, 6, 7, 2, 4],
       [9, 7, 5, 7, 6],
       [1, 2, 9, 2, 7]])

In [149]:
list = [i[0] for i in n[:, 2:3]]
list.sort()
list
for i in range(5):
    n[i,2] = list[i]
    
n

array([[6, 4, 4, 7, 1],
       [1, 2, 5, 5, 8],
       [9, 6, 7, 2, 4],
       [9, 7, 7, 7, 6],
       [1, 2, 9, 2, 7]])

### 11、给定一个4维矩阵，如何得到最后两维的和？

In [4]:
n = np.random.randint(1, 10, size=(4,4,4,4))
n

array([[[[4, 5, 3, 5],
         [5, 2, 1, 3],
         [2, 6, 8, 1],
         [4, 3, 6, 4]],

        [[4, 2, 1, 6],
         [9, 1, 2, 3],
         [9, 7, 8, 6],
         [1, 6, 5, 9]],

        [[1, 6, 9, 7],
         [7, 2, 7, 8],
         [5, 3, 8, 7],
         [4, 2, 6, 4]],

        [[6, 9, 5, 5],
         [8, 7, 4, 5],
         [8, 3, 8, 1],
         [4, 9, 1, 8]]],


       [[[1, 5, 9, 6],
         [2, 3, 8, 7],
         [3, 7, 4, 3],
         [6, 5, 5, 9]],

        [[9, 7, 7, 4],
         [6, 9, 6, 1],
         [6, 9, 1, 6],
         [9, 2, 5, 6]],

        [[4, 5, 5, 2],
         [5, 9, 5, 6],
         [6, 2, 4, 1],
         [7, 3, 1, 4]],

        [[2, 2, 5, 5],
         [9, 8, 4, 6],
         [6, 7, 1, 8],
         [6, 7, 3, 4]]],


       [[[8, 6, 4, 5],
         [7, 9, 2, 5],
         [1, 4, 9, 3],
         [3, 1, 4, 1]],

        [[9, 4, 8, 7],
         [8, 9, 7, 3],
         [7, 2, 4, 3],
         [6, 7, 7, 3]],

        [[3, 6, 4, 6],
         [4, 9, 9, 6],
         [

In [5]:
n.sum(axis=(2,3))

array([[62, 79, 86, 91],
       [83, 93, 69, 83],
       [72, 94, 89, 95],
       [84, 80, 87, 90]])

### 12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [17]:
n12 = np.zeros(shape=(17,), dtype=int)
n12

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
n12[::4] = [1, 2, 3, 4, 5]
n12

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

### 13、给定一个二维矩阵，如何交换其中两行的元素？

In [19]:
n13 = np.random.randint(1, 10, size=(5,5))
n13

array([[8, 7, 5, 8, 5],
       [5, 9, 9, 7, 2],
       [5, 3, 7, 7, 9],
       [4, 7, 6, 3, 9],
       [4, 8, 8, 5, 8]])

In [21]:
n13[0], n13[1] = n13[1].copy(), n13[0].copy()
n13

array([[5, 9, 9, 7, 2],
       [5, 9, 9, 7, 2],
       [5, 3, 7, 7, 9],
       [4, 7, 6, 3, 9],
       [4, 8, 8, 5, 8]])

In [ ]:
# 高级技巧
n13[[1, 2, 1, 2, 3, 4, 0, 1]]

### 14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [203]:
n = np.random.randint(0, 10, size=100000)

In [200]:
def one(n):
    return n*n*n


array([  8,   1,   8, 125, 729, 125, 343,   8,  64,   8,   1,   0, 216,
         0,  27, 216, 512, 512, 125, 125,   0, 729, 343,   8,  64, 125,
         0,   1,   0,   1,   8, 216,   0,   8,   0, 125, 512, 729,   1,
       216,   1,   0, 729,  64,  64, 216, 343,   0, 125, 216, 216, 216,
       125, 216,  64, 512, 729, 125,   8, 512, 729,  64, 125, 125,  27,
       343,  27, 729,  27, 125,  27, 512,   0,   0,  27, 729, 729, 216,
        64, 512,  64,   1, 512, 216,  64,   1, 512,  64,  64, 216, 729,
       729,   1,  64,  27,  64, 125, 729, 125,   1,   8, 343,  27, 512,
       216,  64, 216,  27, 512,   1, 343,  27,  64, 729,   0, 216,   0,
       343,  64,   8, 729,   8,  27, 512, 512, 216,   0,  27, 729, 512,
         0,   0, 729,   8,   8, 125, 343,  27, 729,   0, 729,   0, 729,
        27, 125, 729, 216,   8, 729, 125, 729,   0, 729,   8,   8,  27,
       343, 729,   0, 729, 343, 216, 343,   0,   1,  64, 512, 216, 343,
       125,   1,   0, 729,   8, 729, 729, 216, 216,   8,   8,  2

In [199]:
def two(n):
    return np.power(n,3)


array([  8,   1,   8, 125, 729, 125, 343,   8,  64,   8,   1,   0, 216,
         0,  27, 216, 512, 512, 125, 125,   0, 729, 343,   8,  64, 125,
         0,   1,   0,   1,   8, 216,   0,   8,   0, 125, 512, 729,   1,
       216,   1,   0, 729,  64,  64, 216, 343,   0, 125, 216, 216, 216,
       125, 216,  64, 512, 729, 125,   8, 512, 729,  64, 125, 125,  27,
       343,  27, 729,  27, 125,  27, 512,   0,   0,  27, 729, 729, 216,
        64, 512,  64,   1, 512, 216,  64,   1, 512,  64,  64, 216, 729,
       729,   1,  64,  27,  64, 125, 729, 125,   1,   8, 343,  27, 512,
       216,  64, 216,  27, 512,   1, 343,  27,  64, 729,   0, 216,   0,
       343,  64,   8, 729,   8,  27, 512, 512, 216,   0,  27, 729, 512,
         0,   0, 729,   8,   8, 125, 343,  27, 729,   0, 729,   0, 729,
        27, 125, 729, 216,   8, 729, 125, 729,   0, 729,   8,   8,  27,
       343, 729,   0, 729, 343, 216, 343,   0,   1,  64, 512, 216, 343,
       125,   1,   0, 729,   8, 729, 729, 216, 216,   8,   8,  2

In [204]:
%time one(n)

Wall time: 1.01 ms


array([512,   8,   8, ..., 729, 512,  64])

In [205]:
%time two(n)

Wall time: 998 µs


array([512,   8,   8, ..., 729, 512,  64], dtype=int32)

### 15、创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积

In [206]:
n1 = np.random.randint(0, 10, size=(5,3))
n2 = np.random.randint(0, 10, size=(3,2))
np.dot(n1, n2)

array([[ 48,  96],
       [ 51, 114],
       [ 28,  44],
       [ 40,  86],
       [ 37,  86]])

### 16、矩阵的每一行的元素都减去该行的平均值

In [29]:
n16 = np.random.randint(0, 10, size=(5,5))
n16.mean(axis=1)

array([3. , 3. , 2.4, 5. , 4.8])

In [28]:
n16 = n16 - n16.mean(axis=1).reshape(5,1)
n16

array([[ 2.2,  1.2, -2.8,  1.2, -1.8],
       [ 2.2, -2.8, -1.8, -0.8,  3.2],
       [ 2. ,  2. , -2. ,  0. , -2. ],
       [-3.4,  1.6, -0.4,  2.6, -0.4],
       [-3. , -2. ,  2. ,  3. ,  0. ]])

### 17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：

In [ ]:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

In [236]:
n = np.zeros(shape=(8,8), dtype=int)
n

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [237]:
for i in range(8):
    for j in range(8):
        if i % 2 == 0 and j % 2 == 1:
            n[i, j] = 1
        elif i % 2 ==1 and j % 2 == 0:
            n[i, j] = 1
        else:
            continue

n


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 18、正则化一个5*5随机矩阵
正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

In [39]:
n18 = np.random.randint(0, 10, size=(5, 5))
n18

In [45]:
(n18-n18.min())/(n18.max()-n18.min())



array([[0.375, 0.375, 0.25 , 0.25 , 0.5  ],
       [0.375, 0.875, 0.5  , 0.875, 1.   ],
       [0.   , 0.125, 0.75 , 0.   , 0.75 ],
       [0.5  , 0.125, 0.25 , 0.125, 0.25 ],
       [0.375, 0.75 , 0.625, 0.125, 0.25 ]])

### 20、实现快速和选择排序法

In [55]:
n1 = np.random.randint(0, 10, size=10)
n2 = np.random.randint(0, 10, size=10)
display(n1,n2)

array([5, 6, 7, 6, 6, 3, 1, 2, 3, 9])

array([2, 9, 3, 7, 6, 9, 8, 7, 3, 9])

In [56]:
def quick_sort(n, start, end):
    while start >= end:
        return
    low = start
    high = end
    mid = n[start]
    while low < high:
        while n[high] >= mid and low < high:
            high -= 1

        n[low] = n[high]

        while n[low] < mid and low < high:
            low += 1

        n[high] = n[low]
    n[low] = mid

    quick_sort(n, low+1, end)
    quick_sort(n, start, high-1)
    return n

In [57]:
print(quick_sort(n1, 0, len(n)-1))

[5 6 6 6 7 3 1 2 3 9]


In [58]:
def select(n):
    for i in range(0, len(n)-1):
        for j in range(i+1, len(n)):
            if n[i] > n[j]:
                n[i], n[j] = n[j], n[i]

    return n

In [59]:
print(select(n2))

[2 3 3 6 7 7 8 9 9 9]
